sistema_vet/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Controllers\VacunasController;
use App\Controllers\FormController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
//Route::get('vacunas', 'VacunasController@index');
Route::resource('vacunas','VacunasController');
//Route::resource('forms','FormController');
Route::get('forms', 'FormController@create');
Route::post('forms', 'FormController@store');
//Route::post('/vacunas/store', 'VacunasController@store')->name('vacunas.store');

//Route::get('/vacunas/store/{id_vacuna}', 'VacunasController@edit')->name('vacunas.edit');
//Route::post('/vacunas/update/{id_vacuna}', 'VacunasController@update')->name('vacunas.update');

Route::post('/vacunas/eliminar_ajax/{id_vacuna}', 'VacunasController@destroy_ajax')->name('vacunas.eliminar_ajax');


//Route::get('/vacunas', 'App\Http\Controllers\VacunasController@index');
//Route::get('/vacunas', [VacunasController::class,'index']);

sistema_vet/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

sistema_vet/app/Models/Vacunas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Vacunas extends Model
{
    use HasFactory;
    protected $table = 'vacunas';
    protected $primaryKey = 'id_vacuna';
    protected $fillable = ['nombre_vacuna', 'fecha_vacuna', 'descripcion_vacuna'];

}

sistema_vet/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

sistema_vet/app/Http/Controllers/FormController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Mail\MessageRecieved;
use Illuminate\Support\Facades\Mail;

class FormController extends Controller
{
    public function create()
    {
        return view('emails.form');
    }
    public function store(Request $request)
    {
        $out = new \Symfony\Component\Console\Output\ConsoleOutput();
        $out->writeln($request->all());
        $cuerpo=$request->all();
        $out->writeln('........................');
        $out->writeln($cuerpo['correo']);
        Mail::to($cuerpo['correo'])->send(new MessageRecieved($cuerpo));
        
        return 'Mensaje enviado';

    }
    //
}

sistema_vet/app/Http/Controllers/VacunasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Vacunas; // Instanciamos el modelo Vacunas
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use DB;
use Input;
use Storage;
use Illuminate\Support\Facades\Session;


class VacunasController extends Controller
{
    public function index()
    {
        //$vacunas = Vacunas::all();
        $vacunas = DB::table('vacunas')->get();
        return view('vacunas.master', compact('vacunas'));

        //return 'Holaa';
    }
    public function create()
    {
        return view('vacunas.create');
    }
    public function store(Request $request)
    {
        //$storeData=$request->validate([ 'nombre_vacuna' => 'required', 'fecha_vacuna' => 'required','descripcion_vacuna' => 'required',]);
        //$vacuna=Vacunas::create($storeData);
        
        $vacuna = new Vacunas;
        $vacuna->create($request->all());
        return redirect('vacunas');
        //return redirect()->route('vacunas.index');
    }

    public function edit($id_vacuna)
    {
        $vacuna = Vacunas::findOrFail($id_vacuna);
        return view('vacunas.edit',compact($vacuna));
    }
    public function update(ItemUpdateRequest $request, $id_vacuna)
    {        
        $storeData=$request->validate([
            'nombre_vacuna' => 'required',
            'fecha_vacuna' => 'required',
            'descripcion_vacuna' => 'required',
        ]);
        Vacunas::whereId($id_vacuna)->update($storeData);
        return redirect('/vacunas');
    }
    public function destroy($id_vacuna)
    {
        //$vacuna = Vacunas::findOrFail($id_vacuna);

        //$vacuna->delete();
        $vacuna = Vacunas::findOrFail($id_vacuna);
        $vacuna->delete();
        return redirect('vacunas')->with('deleted','Eliminado');
    }
    public function destroy_ajax($id_vacuna)
    {
        $vacuna = Vacunas::findOrFail($id_vacuna);
        $vacuna->delete();
        return response()->json(['success'=>'Eliminado']);
    }

}

sistema_vet/resources/views/vacunas/create.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css"/>  
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <link id="bs-css" href="https://netdna.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link id="bsdp-css" href="https://unpkg.com/bootstrap-datepicker@1.9.0/dist/css/bootstrap-datepicker3.min.css" rel="stylesheet">
    
    <title>Clinica Veterinaria MEW</title>
  </head>
    <div class="container"> <div class=" text-center mt-5 ">
      <h1>Crear vacuna</h1>

      <form method="post" action="{{ route('vacunas.store') }}" >
      
        <div class="mb-3 row">
          @csrf
          <label for="input" class="col-sm-2 col-form-label">Nombre de vacuna</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" name="nombre_vacuna" id="nombre_vacuna">
          </div>
        </div>

        <div class="mb-3 row">
          <label for="inputdesc" class="col-sm-2 col-form-label">Fecha de vacuna</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" name="fecha_vacuna" id="fecha_vacuna">
          </div>
          
        </div>

        <div class="mb-3 row">
          <label for="inputdesc" class="col-sm-2 col-form-label">Descripción de vacuna</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" name="descripcion_vacuna" id="descripcion_vacuna">
          </div>
        </div>
        
        <button type="submit" class="btn btn-default">Guardar</button>

      </form>
      <a href="{{ route('vacunas.index')}}" class="btn btn-warning m-1" >Regresar</a>

    </div>

    </html>

sistema_vet/resources/views/vacunas/edit.blade.php
@extends('layouts.master')

@section('title', 'Editar vacuna')

    @section('content')
    <form action="{{ route('vacunas.update', $vacuna->id_vacuna) }}" method="POST">
        <input type="hidden" name="_method" value="PUT">
        @csrf

        <div class="mb-3 row">
          <label for="input" class="col-sm-2 col-form-label">Nombre de vacuna</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="nombre_vacuna">
          </div>
        </div>

        <div class="mb-3 row">
          <label for="inputdesc" class="col-sm-2 col-form-label">Fecha de vacuna</label>
              <div class='col-sm-6'>
                  <div class="form-group">
                      <div class='input-group date' id='fecha_vacuna'>
                          <input type='text' class="form-control" />
                          <span class="input-group-addon">
                              <span class="glyphicon glyphicon-calendar"></span>
                          </span>
                      </div>
                  </div>
              </div>
        </div>

        <div class="mb-3 row">
          <label for="inputdesc" class="col-sm-2 col-form-label">Descripción de vacuna</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="descripcion_vacuna">
          </div>
        </div>

        <button type="submit" class="btn btn-default">Guardar</button>

      </form>
    @endsection

sistema_vet/resources/views/vacunas/master.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css"/>  
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <link id="bs-css" href="https://netdna.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link id="bsdp-css" href="https://unpkg.com/bootstrap-datepicker@1.9.0/dist/css/bootstrap-datepicker3.min.css" rel="stylesheet">
    
    <title>Clinica Veterinaria MEW</title>
  </head>
  <body>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

        <div class="container">
            <hr/>
            <hr/>
            @php
            echo date('l jS \of F Y h:i:s A');
            echo '<br>';    
            @endphp
          <a href="{{ route('vacunas.create')}}" class="btn btn-primary m-1" >Crear nueva</a>
          <hr/>
          <table id="laravel_crud" class="table">
              <thead>
              <th>Nombre de vacuna</th>
              <th>Fecha de vacunacion</th>
              <th>Descripcion de vacuna</th>
              <th colspan="3">Actions</th>
              </thead>
      
              @foreach($vacunas as $vacuna)
                  <tr id="row_{{$vacuna->id_vacuna}}">
                      <td>{{$vacuna->nombre_vacuna}}</td>
                      <td>{{$vacuna->fecha_vacuna}}</td>
                      <td>{{$vacuna->descripcion_vacuna}}</td>
                      <td>
                          <div class="d-flex">
                              <form action="{{ route('vacunas.destroy',[$vacuna->id_vacuna]) }}" method="POST">
                                  <a class="btn btn-warning" href="{{ route('vacunas.edit',[$vacuna->id_vacuna]) }}" role="button">Editar</a>
                                  @csrf
                                  @method('DELETE')
                                  <button type="submit" class="btn btn-danger m-1">Eliminar</button>
                                  <a href="javascript:void(0)" class="btn btn-danger m-1" id="button_ajax"  onclick="delete_ajax(12)" role="button">Eliminar AJAX</a>
                              </form>
                              
                          </div>
                      </td>
                  </tr>
      
              @endforeach
          </table>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
        <script src=”script.js” language=”Javascript”>
            $('#laravel_crud').DataTable();
            var token = $("meta[name='csrf-token']").attr("content");
            $(document).ready(function(){
                function delete_ajax(id_v) {
                    $.ajax({
                        url: "vacunas/eliminar_ajax/"+id_v,
                        type: 'POST',
                        data : {id_vacuna:id_v},
                        beforeSend: function(xhr){
                            xhr.setRequestHeader('X-CSRF-Token',$('[name="_csrfToken"]').val());
                        },
                        success: function(data) {
                            $("#row_"+id).remove();
                            $("#laravel_crud").DataTable().ajax.reload();
                        },
                        dataType: 'json'    
                    });
                }
            });
        </script>
  </body>
  
</html>